name: Build and Test Script for Logic

on:							
  push:
    branches: [ "main" ]			

jobs:
  test:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: Run Test Cases
        run: make logic_test; ./logic_test_script >test_results.txt; gcov logic_test-logic.c

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Uploads
          path: |
            ./logic_test
            ./test_results.txt
            ./*.gcov