name: Build and Test Script for Logic

on:							
  push:
    branches: [ "main" ]			

jobs:
  test:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: Set up GTK 3
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev pkg-config

      - name: Run Test Cases
        run: make logic_test; ./logic_test_script >test_results.txt; gcov logic_test-logic.c

      - name: Run board test cases
        run: make board_test; ./board_test_script >board_test_results.txt; gcov board_test-board.c

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Uploads
          path: |
            ./logic_test
            ./test_results.txt
            ./*.gcov

      - name: Upload board results
        uses: actions/upload-artifact@v4
        with:
          name: Uploads
          path: |
            ./board_tests/board_test
            ./board_test_results.txt
            ./*.gcov
