name: Build and Test Script for Logic

on:							
  push:
    branches: [ "main" ]			

jobs:
  test:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: Set up GTK 3
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev pkg-config

      - name: Run logic Test Cases
        run: make logic_test; ./logic_test_script >test_results.txt; gcov logic_test-logic.c
        
      - name: Run score Test Cases
        run: make score_test; ./score_test_script.sh >score_test_results.txt; gcov score_test-score.c

      - name: Run output Test Cases
        run: make output_test; ./output_test_script >output_test_results.txt; gcov output_test-output.c

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Uploads
          path: |
            ./logic_test
            ./test_results.txt
            ./*.gcov
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: output test results
          path: |
            ./output_test
            ./output_test_results.txt
            ./*.gcov
